### ISSUE TITLE
Upgrade Linq2db

### ISSUE THREAD

**Issue by CumpsD** [akkadotnet/Akka.Persistence.Linq2Db#165]
Creating this issue to follow up the problems with sqlite in upgrading linq2db.

All information is in the comments from https://github.com/akkadotnet/Akka.Persistence.Sql/pull/163#issuecomment-1475507465

We want to upgrade linq2db, but can't get past 3.5.0 because then sqlite explodes with some DateTime related issues.

**Comment by mhu2022** [comment]
Hello, I would like to know when the 'Linq2db' with dependencies to Akka.Net v1.5.1 will be released. We would like to use it with Sql Server.

**Comment by Aaronontheweb** [comment]
> Hello, I would like to know when the 'Linq2db' with dependencies to Akka.Net v1.5.1 will be released. We would like to use it with Sql Server.

@Arkatufus is working on a project plan today that should address this: https://github.com/orgs/akkadotnet/projects/9 <-- first beta release

**Comment by CumpsD** [comment]
The https://github.com/orgs/akkadotnet/projects/9 link is probably private? Doesn't work here
