### ISSUE TITLE
Compatibility with Akka.Persistence.MySql

### ISSUE THREAD

**Issue by to11mtm** [akkadotnet/Akka.Persistence.Linq2Db#3]
We do not have a configuration or a compatibility spec to work with Akka.Persistence.MySql.

In theory, a user would be able to manually configure the tables with `delete-compatibility-mode`, but we should provide easy configuration and ideally provide unit tests.

We should make sure such integration/implementation uses a MySql connector and Implementation packages that are non-encumbering (i.e. we should steer users away from adopting the Oracle MySqlConnector, but rather an MIT or Apache based one, consider MariaDB or similar instead of vanilla MySql)

**Comment by Arkatufus** [comment]
Added in the data compatibility PR #117
